### ISSUE TITLE
Missing default recipe

### ISSUE THREAD

**Issue by mattse** [klamontagne/chef-google_auth_proxy#7]
I'm having trouble using your chef recipe.  I've created a new cookbook and included your
```
include_recipe "google_auth_proxy"

google_auth_proxy_install "my-app" do
...
```
lines exactly in my cookbook.  I've also added a `depends 'google_auth_proxy'` line to my cookbook's `metadata.rb`.  When I try to run the cookbook, I get:
```
================================================================================
  Recipe Compile Error
  ================================================================================

  Chef::Exceptions::RecipeNotFound
  --------------------------------
  could not find recipe default for cookbook google_auth_proxy
```

It seems that this cookbook doesn't have a `recipes/default.rb` recipe like other cookbooks, and so my depends line is breaking.  

I'm fairly new to Chef, so if there's something that I'm doing incorrectly to include your Cookbook, I'd appreciate your help.  

UPDATE:

I've managed to fix this by adding a blank recipes/default.rb file to the repository.  Perhaps consider adding this to fix compatibility with cookbook package managers like Berkshelf.

**Comment by klamontagne** [comment]
Hi, sorry about that, The `include_recipe`is not necessary actually, adding a `depends` makes the `google_auth_proxy_install`resource available.
